"""
Django settings for maapi_www project.

Generated by 'django-admin startproject' using Django 1.8.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import os.path

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '62m+8*(=q=3sf#i+yyf9=*2(c9i)ck6-00!3zonqdnm_2)=zuk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['maapi.pl','192.168.1.110']


# Application definition

INSTALLED_APPS = (
    'django.contrib.humanize',
    'maapi',
    'bootstrap3',
    'admin_honeypot',
    'admin_reorder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)
MIDDLEWARE_CLASSES = (
    'admin_reorder.middleware.ModelAdminReorder',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
)
ROOT_URLCONF = 'maapi_www.urls'

LOGIN_REDIRECT_URL = 'index'
TEMPLATES = [
    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',
#        'DIRS': ['/var/www/html/maapi_www/maapi/templates'],
        'DIRS': [  '/home/apache/maapi_www/maapi/templates'

                ],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maapi_www.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'MaaPi',
        'USER': 'maapi_db',
        'PASSWORD': '889192',
        'HOST': 'localhost',
        'PORT': '5432',
    }


}

LANGUAGE_CODE = 'Pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

#STATICFILES_DIRS = (
    #os.path.join(PROJECT_ROOT, 'static'),
#)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, "static/")
ADMIN_MEDIA_PREFIX = '/static/admin/'


ADMIN_REORDER = (
    # Rename app
    {'app': 'maapi', 'label': 'Settings',
         'models': ('maapi.Devices',
                    'maapi.SensorsList',
                    'maapi.DList',
                    'maapi.MainScreen',
                    'maapi.MaapiFuturesModel'
                    )
        },



    {'app': 'maapi', 'label': 'Triggers',
         'models': (
                    'maapi.MathModel',
                    'maapi.CommandLine',
                    'maapi.SwitchModel',
                    'maapi.MailWachDog',
                    )
        },




    {'app': 'maapi', 'label': 'Settings - Lists',
         'models': ('maapi.ScanedOneWireListModel',

                    'maapi.Groups',
                    'maapi.Units',
                    'maapi.Locations',
                    'maapi.MachineLocation',
                    'maapi.BusTypes',
                    'maapi.MailingList',
                    'maapi.BackgroudListModel',
                    )
    },
        {'app': 'maapi', 'label': 'System Settings',
             'models': (
                        'maapi.CronModel',
                        'maapi.PortListenerModel',
                        )
            },
    {'app': 'auth', 'label': 'Authorisation'},



    # Reorder app models
#    {'app': 'auth', 'models': ('auth.User', 'auth.Group')},

    # Exclude models
#    {'app': 'auth', 'models': ('auth.User', )},

    # Cross-linked models
#    {'app': 'auth', 'models': ('auth.User', 'sites.Site')},

    # models with custom name
#    {'app': 'auth', 'models': (
#        'auth.Group',
#        {'model': 'auth.User', 'label': 'Staff'},
#    )},
)
